In [1]:
from zipfile import ZipFile
from urllib.request import urlopen   
import pandas as pd
import os
import zipfile

In [2]:
URL1 = \
    'https://download.cms.gov/marketplace-puf/2018/benefits-and-cost-sharing-puf.zip'

# open and save the zip file onto computer
url1 = urlopen(URL1)
output = open('benefits-and-cost-sharing-puf.zip', 'wb')    # note the flag:  "wb"        
output.write(url1.read())
output.close()

# read the zip file as a pandas dataframe
benefit_cost = pd.read_csv('benefits-and-cost-sharing-puf.zip', encoding='cp1252')   # pandas version 0.18.1 takes zip files       

# if keeping on disk the zip file is not wanted, then:
#os.remove(zipName)   # remove the copy of the zipfile on diskbenefit_cost.head()
benefit_cost.info()

/Users/yagmurbali/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (9,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 829652 entries, 0 to 829651
Data columns (total 24 columns):
BusinessYear           829652 non-null int64
StateCode              829652 non-null object
IssuerId               829652 non-null int64
SourceName             829652 non-null object
ImportDate             829652 non-null object
StandardComponentId    829652 non-null object
PlanId                 829652 non-null object
BenefitName            829652 non-null object
CopayInnTier1          646629 non-null object
CopayInnTier2          121865 non-null object
CopayOutofNet          646629 non-null object
CoinsInnTier1          646629 non-null object
CoinsInnTier2          121865 non-null object
CoinsOutofNet          646629 non-null object
IsEHB                  615591 non-null object
IsCovered              798353 non-null object
QuantLimitOnSvc        243338 non-null object
LimitQty               116726 non-null float64
LimitUnit              116714 non-null object
Exclusions             46650 non-null object
Explanation            256235 non-null object
EHBVarReason           230623 non-null object
IsExclFromInnMOOP      690359 non-null object
IsExclFromOonMOOP      690363 non-null object
dtypes: float64(1), int64(2), object(21)
memory usage: 151.9+ MB

In [3]:
URL2 = \
    'https://download.cms.gov/marketplace-puf/2018/rate-puf.zip'

# open and save the zip file onto computer
url2 = urlopen(URL2)
output = open('rate-puf.zip', 'wb')    # note the flag:  "wb"        
output.write(url2.read())
output.close()

# read the zip file as a pandas dataframe
rate = pd.read_csv('rate-puf.zip', encoding='cp1252')   # pandas version 0.18.1 takes zip files       

# if keeping on disk the zip file is not wanted, then:
#os.remove(zipName)   # remove the copy of the zipfile on diskbenefit_cost.head()
rate.head()

,BusinessYear,StateCode,IssuerId,SourceName,ImportDate,FederalTIN,RateEffectiveDate,RateExpirationDate,PlanId,RatingAreaId,...,Age,IndividualRate,IndividualTobaccoRate,Couple,PrimarySubscriberAndOneDependent,PrimarySubscriberAndTwoDependents,PrimarySubscriberAndThreeOrMoreDependents,CoupleAndOneDependent,CoupleAndTwoDependents,CoupleAndThreeOrMoreDependents
0,2018,AK,21989,HIOS,2017-09-26 02:21:16,93-0438772,2018-01-01,2018-12-31,21989AK0030001,Rating Area 1,...,0-14,53.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018,AK,21989,HIOS,2017-09-26 02:21:16,93-0438772,2018-01-01,2018-03-31,21989AK0090001,Rating Area 1,...,0-14,63.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018,AK,21989,HIOS,2017-09-26 02:21:16,93-0438772,2018-04-01,2018-06-30,21989AK0090001,Rating Area 1,...,0-14,64.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018,AK,21989,HIOS,2017-09-26 02:21:16,93-0438772,2018-07-01,2018-09-30,21989AK0090001,Rating Area 1,...,0-14,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018,AK,21989,HIOS,2017-09-26 02:21:16,93-0438772,2018-10-01,2018-12-31,21989AK0090001,Rating Area 1,...,0-14,66.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
URL3 = \
    'https://download.cms.gov/marketplace-puf/2018/business-rules-puf.zip'

# open and save the zip file onto computer
url3 = urlopen(URL3)
output = open('business-rules-puf.zip', 'wb')    # note the flag:  "wb"        
output.write(url3.read())
output.close()

# read the zip file as a pandas dataframe
business_rules = pd.read_csv('business-rules-puf.zip', encoding='cp1252')   # pandas version 0.18.1 takes zip files       

# if keeping on disk the zip file is not wanted, then:
#os.remove(zipName)   # remove the copy of the zipfile on diskbenefit_cost.head()
business_rules.head()

,BusinessYear,StateCode,IssuerId,SourceName,ImportDate,TIN,ProductId,StandardComponentId,EnrolleeContractRateDeterminationRule,TwoParentFamilyMaxDependentsRule,SingleParentFamilyMaxDependentsRule,DependentMaximumAgRule,ChildrenOnlyContractMaxChildrenRule,DomesticPartnerAsSpouseIndicator,SameSexPartnerAsSpouseIndicator,AgeDeterminationRule,MinimumTobaccoFreeMonthsRule,CohabitationRule,MarketCoverage,DentalOnlyPlan
0,2018,AK,21989,HIOS,2017-09-26 02:21:16,93-0438772,21989AK003,21989AK0030001,A different rate (specifically for parties of ...,3 or more,3 or more,25,3 or more,Yes,Yes,Age on effective date,Not Applicable,"Spouse,No;Grandson or Granddaughter,No;Adopted...",Individual,Yes
1,2018,AK,21989,HIOS,2017-09-26 02:21:16,93-0438772,21989AK005,21989AK0050001,A different rate (specifically for parties of ...,3 or more,3 or more,25,3 or more,Yes,Yes,Age on effective date,Not Applicable,"Spouse,No;Grandson or Granddaughter,No;Adopted...",Individual,Yes
2,2018,AK,21989,HIOS,2017-09-26 02:21:16,93-0438772,21989AK005,21989AK0050002,A different rate (specifically for parties of ...,3 or more,3 or more,25,3 or more,Yes,Yes,Age on effective date,Not Applicable,"Spouse,No;Grandson or Granddaughter,No;Adopted...",Individual,Yes
3,2018,AK,21989,HIOS,2017-09-26 02:21:16,93-0438772,21989AK007,21989AK0070001,A different rate (specifically for parties of ...,3 or more,3 or more,25,3 or more,Yes,Yes,Age on effective date,Not Applicable,"Spouse,No;Grandson or Granddaughter,No;Adopted...",Individual,Yes
4,2018,AK,21989,HIOS,2017-09-26 02:21:16,93-0438772,21989AK008,21989AK0080001,There are rates specifically for couples and f...,3 or more,3 or more,25,3 or more,Yes,Yes,Age on effective date,Not Applicable,"Spouse,No;Grandson or Granddaughter,No;Adopted...",SHOP (Small Group),Yes

In [5]:
URL4 = \
    'https://download.cms.gov/marketplace-puf/2018/service-area-puf.zip'

# open and save the zip file onto computer
url4 = urlopen(URL4)
output = open('service-area-puf.zip', 'wb')    # note the flag:  "wb"        
output.write(url4.read())
output.close()

# read the zip file as a pandas dataframe
service_area = pd.read_csv('service-area-puf.zip', encoding='cp1252')   # pandas version 0.18.1 takes zip files       

# if keeping on disk the zip file is not wanted, then:
#os.remove(zipName)   # remove the copy of the zipfile on diskbenefit_cost.head()
service_area.head()

,BusinessYear,StateCode,IssuerId,SourceName,ImportDate,ServiceAreaId,ServiceAreaName,CoverEntireState,County,PartialCounty,ZipCodes,PartialCountyJustification,MarketCoverage,DentalOnlyPlan
0,2018,WI,86584,HIOS,2017-08-05 02:21:19,WIS001,AspirusArise,No,55115.0,Yes,"54408, 54409, 54414, 54416, 54427, 54450, 5448...",86584_WI_service_area_partial_county.pdf,NaN,NaN
1,2018,WI,87416,HIOS,2018-01-18 02:20:16,WIS001,CGHC Service Area,No,55009.0,No,NaN,NaN,NaN,NaN
2,2018,WI,87416,HIOS,2018-01-18 02:20:16,WIS001,CGHC Service Area,No,55015.0,No,NaN,NaN,NaN,NaN
3,2018,WI,87416,HIOS,2018-01-18 02:20:16,WIS001,CGHC Service Area,No,55029.0,No,NaN,NaN,NaN,NaN
4,2018,WI,87416,HIOS,2018-01-18 02:20:16,WIS001,CGHC Service Area,No,55039.0,No,NaN,NaN,NaN,NaN

In [6]:
URL5 = \
    'https://download.cms.gov/marketplace-puf/2018/network-puf.zip'

# open and save the zip file onto computer
url5 = urlopen(URL5)
output = open('network-puf.zip', 'wb')    # note the flag:  "wb"        
output.write(url5.read())
output.close()

# read the zip file as a pandas dataframe
network = pd.read_csv('network-puf.zip', encoding='cp1252')   # pandas version 0.18.1 takes zip files       

# if keeping on disk the zip file is not wanted, then:
#os.remove(zipName)   # remove the copy of the zipfile on diskbenefit_cost.head()
network.head()

,BusinessYear,StateCode,IssuerId,SourceName,ImportDate,NetworkName,NetworkId,NetworkURL,MarketCoverage,DentalOnlyPlan
0,2018,AK,21989,HIOS,2017-09-26 02:21:16,Delta Dental Premier,AKN001,https://www.modahealth.com/shop/provider-searc...,NaN,NaN
1,2018,AK,21989,HIOS,2017-09-26 02:21:16,Delta Dental PPO,AKN002,https://www.modahealth.com/shop/provider-searc...,NaN,NaN
2,2018,AK,38344,HIOS,2017-11-01 02:20:20,HeritagePlus and Dental Choice,AKN001,https://premera.vitalschoice.com/?ci=premeraak...,NaN,NaN
3,2018,AK,73836,HIOS,2017-09-02 02:21:27,Endeavor Providence,AKN002,https://www.modahealth.com/ProviderSearch?prod...,NaN,NaN
4,2018,AK,73836,HIOS,2017-09-02 02:21:27,Endeavor Select,AKN001,https://www.modahealth.com/ProviderSearch?prod...,NaN,NaN

In [7]:
URL6 = \
    'https://download.cms.gov/marketplace-puf/2018/plan-attributes-puf.zip'

# open and save the zip file onto computer
url6 = urlopen(URL6)
output = open('plan-attributes-puf.zip', 'wb')    # note the flag:  "wb"        
output.write(url6.read())
output.close()

# read the zip file as a pandas dataframe
plan_attributes = pd.read_csv('plan-attributes-puf.zip', encoding='cp1252')   # pandas version 0.18.1 takes zip files       

# if keeping on disk the zip file is not wanted, then:
#os.remove(zipName)   # remove the copy of the zipfile on diskbenefit_cost.head()
plan_attributes.head()

/Users/yagmurbali/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (81,82,83,87,88,89,90,91,92,112,123,124,125,126,149) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,BusinessYear,StateCode,IssuerId,SourceName,ImportDate,MarketCoverage,DentalOnlyPlan,TIN,StandardComponentId,PlanMarketingName,...,TEHBDedOutOfNetFamilyPerPerson,TEHBDedOutOfNetFamilyPerGroup,TEHBDedCombInnOonIndividual,TEHBDedCombInnOonFamilyPerPerson,TEHBDedCombInnOonFamilyPerGroup,IsHSAEligible,HSAOrHRAEmployerContribution,HSAOrHRAEmployerContributionAmount,URLForSummaryofBenefitsCoverage,PlanBrochure
0,2018,AK,21989,HIOS,2017-09-26 02:21:16,SHOP (Small Group),Yes,93-0438772,21989AK0130001,"Delta Dental Premier, +2000, 100*/80/50, 50, PF",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.modahealth.com/pdfs/ben_sum/AK/170...
1,2018,AK,21989,HIOS,2017-09-26 02:21:16,Individual,Yes,93-0438772,21989AK0030001,Delta Dental Premier Plan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.modahealth.com/pdfs/plans/individu...
2,2018,AK,21989,HIOS,2017-09-26 02:21:16,Individual,Yes,93-0438772,21989AK0030001,Delta Dental Premier Plan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.modahealth.com/pdfs/plans/individu...
3,2018,AK,21989,HIOS,2017-09-26 02:21:16,SHOP (Small Group),Yes,93-0438772,21989AK0130002,"Delta Dental Premier, +2500, 100*/80/50, 50, PF",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.modahealth.com/pdfs/ben_sum/AK/170...
4,2018,AK,21989,HIOS,2017-09-26 02:21:16,SHOP (Small Group),Yes,93-0438772,21989AK0080001,"Delta Dental Premier 1000, 100*/80/50, 50",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.modahealth.com/pdfs/ben_sum/AK/170...

In [8]:
rate.groupby(['Tobacco', 'IndividualTobaccoRate', 'IndividualRate']).count().sample()

,,,BusinessYear,StateCode,IssuerId,SourceName,ImportDate,FederalTIN,RateEffectiveDate,RateExpirationDate,PlanId,RatingAreaId,Age,Couple,PrimarySubscriberAndOneDependent,PrimarySubscriberAndTwoDependents,PrimarySubscriberAndThreeOrMoreDependents,CoupleAndOneDependent,CoupleAndTwoDependents,CoupleAndThreeOrMoreDependents
Tobacco,IndividualTobaccoRate,IndividualRate,,,,,,,,,,,,,,,,,,
Tobacco User/Non-Tobacco User,508.58,479.79,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0

In [9]:
#There are 39 state
rate.StateCode.unique()

array(['AK', 'AL', 'AZ', 'FL', 'GA', 'IN', 'LA', 'MO', 'MS', 'NC', 'ND',
       'NJ', 'OK', 'SC', 'TN', 'TX', 'WI', 'WY', 'AR', 'DE', 'HI', 'IA',
       'IL', 'KS', 'KY', 'ME', 'MI', 'MT', 'NE', 'NH', 'NM', 'NV', 'OH',
       'OR', 'PA', 'SD', 'UT', 'VA', 'WV'], dtype=object)

In [10]:
# If we take a quick look at the IndividualRate column, we will see there are few rates over 9000. It might be written wrong
rate[rate.IndividualRate>9000].IndividualRate.count()

5954

In [11]:
rate.Tobacco.sample(50)
rate.groupby(['Tobacco']).count()

,BusinessYear,StateCode,IssuerId,SourceName,ImportDate,FederalTIN,RateEffectiveDate,RateExpirationDate,PlanId,RatingAreaId,Age,IndividualRate,IndividualTobaccoRate,Couple,PrimarySubscriberAndOneDependent,PrimarySubscriberAndTwoDependents,PrimarySubscriberAndThreeOrMoreDependents,CoupleAndOneDependent,CoupleAndTwoDependents,CoupleAndThreeOrMoreDependents
Tobacco,,,,,,,,,,,,,,,,,,,,
No Preference,1768782,1768782,1768782,1768782,1768782,1768782,1768782,1768782,1768782,1768782,1768782,1768782,0,0,0,0,0,0,0,0
Tobacco User/Non-Tobacco User,517599,517599,517599,517599,517599,517599,517599,517599,517599,517599,517599,517599,517599,0,0,0,0,0,0,0

In [12]:
benefit_cost.groupby(['QuantLimitOnSvc']).count().tail(100)

,BusinessYear,StateCode,IssuerId,SourceName,ImportDate,StandardComponentId,PlanId,BenefitName,CopayInnTier1,CopayInnTier2,...,CoinsOutofNet,IsEHB,IsCovered,LimitQty,LimitUnit,Exclusions,Explanation,EHBVarReason,IsExclFromInnMOOP,IsExclFromOonMOOP
QuantLimitOnSvc,,,,,,,,,,,,,,,,,,,,,
No,128317,128317,128317,128317,128317,128317,128317,128317,124448,4305,...,124448,111387,128317,0,0,12940,44762,30181,125153,125153
Yes,115021,115021,115021,115021,115021,115021,115021,115021,114739,21377,...,114739,104573,115021,115021,115021,8532,72718,75895,114847,114847

In [13]:
planAttributes= plan_attributes[['IssuerId','MetalLevel', 'DentalOnlyPlan', 'MarketCoverage', 'StateCode']]
planAttributes.head()

   IssuerId MetalLevel DentalOnlyPlan      MarketCoverage StateCode
0     21989       High            Yes  SHOP (Small Group)        AK
1     21989        Low            Yes          Individual        AK
2     21989        Low            Yes          Individual        AK
3     21989       High            Yes  SHOP (Small Group)        AK
4     21989       High            Yes  SHOP (Small Group)        AK

In [14]:
rate_= rate[['Age', 'Tobacco', 'IndividualRate', 'IndividualTobaccoRate']]
rate_.head()

    Age        Tobacco  IndividualRate  IndividualTobaccoRate
0  0-14  No Preference            53.0                    NaN
1  0-14  No Preference            63.0                    NaN
2  0-14  No Preference            64.0                    NaN
3  0-14  No Preference            65.0                    NaN
4  0-14  No Preference            66.0                    NaN

In [15]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.truncate.html
rate_ = rate_.truncate(after=14999)

In [16]:
benefitCost= benefit_cost[['IssuerId','BenefitName', 'IsCovered', 'IsEHB', 'QuantLimitOnSvc', 'IsExclFromInnMOOP', 'IsExclFromOonMOOP']]
benefitCost.head()

,IssuerId,BenefitName,IsCovered,IsEHB,QuantLimitOnSvc,IsExclFromInnMOOP,IsExclFromOonMOOP
0,21989,Routine Dental Services (Adult),Covered,NaN,Yes,No,No
1,21989,Dental Check-Up for Children,Covered,Yes,Yes,No,No
2,21989,Basic Dental Care - Child,Covered,Yes,NaN,No,No
3,21989,Orthodontia - Child,Covered,Yes,NaN,No,No
4,21989,Major Dental Care - Child,Covered,Yes,NaN,No,No

In [17]:
benefitCost = benefitCost.truncate(after=14999)

In [18]:
merged = pd.concat([rate_, benefitCost], axis=1)

In [19]:
healthInsurance = pd.merge(merged, planAttributes, on='IssuerId')

In [20]:
healthInsurance.head()

,Age,Tobacco,IndividualRate,IndividualTobaccoRate,IssuerId,BenefitName,IsCovered,IsEHB,QuantLimitOnSvc,IsExclFromInnMOOP,IsExclFromOonMOOP,MetalLevel,DentalOnlyPlan,MarketCoverage,StateCode
0,0-14,No Preference,53.0,NaN,21989,Routine Dental Services (Adult),Covered,NaN,Yes,No,No,High,Yes,SHOP (Small Group),AK
1,0-14,No Preference,53.0,NaN,21989,Routine Dental Services (Adult),Covered,NaN,Yes,No,No,Low,Yes,Individual,AK
2,0-14,No Preference,53.0,NaN,21989,Routine Dental Services (Adult),Covered,NaN,Yes,No,No,Low,Yes,Individual,AK
3,0-14,No Preference,53.0,NaN,21989,Routine Dental Services (Adult),Covered,NaN,Yes,No,No,High,Yes,SHOP (Small Group),AK
4,0-14,No Preference,53.0,NaN,21989,Routine Dental Services (Adult),Covered,NaN,Yes,No,No,High,Yes,SHOP (Small Group),AK

In [21]:
healthInsurance.to_csv('healthInsurance.csv')